### ISSUE TITLE
shortcut: 'Shift + Click'

### ISSUE THREAD

**Issue by KuiyueRO** [dpickett/open-related-url#5]
I had an idea that Obsidian's CTRL + click would open documents, and we could shift click to open web pages quickly.

This allows us to easily make web bookmarks.

**Comment by dredhorse** [comment]
or a right click 😀

**Comment by dpickett** [comment]
thanks for filing an issue. This likely requires extending the [viewport](https://marcus.se.net/obsidian-plugin-docs/editor/extensions/view-plugins). While this would be a nice feature, it's likely a different plugin that enhances the UI of obsidian. I'm going to close this out.
